### ISSUE TITLE
MatrixParams do not work

### ISSUE THREAD

**Issue by murphy-paul** [krasserm/grails-jaxrs#29]
It appears that the plugin is appending and '/' to the end of URLS when causes jersey to fail to when resolving the matrix params.

See MatrixParamInjectableProvider.getValue. This method will only look at the last Path segment. And an extra path segment is added because of the '/'

See UriComponent.decodePath at line 595.
e = path.indexOf('/', s) will cause the matrix params to be resolve in the do while loop. After the loop the if(s < path.length()) condition is false and an extra Empty Path segment is added.

Great plugin by the way.

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#5
