### ISSUE TITLE
Spring Security and JAX-RS, access denied to api URLs

### ISSUE THREAD

**Issue by shnatyk** [krasserm/grails-jaxrs#40]
Hi,

I am beginner with Grails and struggling some problem with combining REST api and Spring Security for my web application (grails version: 2.2.4). 

Before creating API I created registration and authentication system and all works fine. About REST, till now I have tried two ways, one according to documentation (http://www.grails.org/doc/2.2.x/guide/webServices.html), second by using JAX-RS plugin. In both ways I go thorugh all needed steps without problems till I try to test if any api's URL works, I always got this message in browser: "Sorry, you are not authorized to view this page", even if I am logged in as the admin (ROLE_ADMIN).

I tried to add some static rule or intercepturlmap to config.groovy file but nothing have helped. 

Please help me, give any clues, suggestions, every reply very appreciated!

Seb

**Comment by erickmelo** [comment]
Can i use annotations to secure my resources or have I to use UrlMappings for that?

**Comment by michaelrice** [comment]
@erickmelo did you try this plugin? https://github.com/budjb/grails-jaxrs-security

**Comment by erickmelo** [comment]
The documentation is off-line (broken link): Error 404 (http://budjb.github.io/grails-spring-security-jaxrs/doc/manual/index.html)

**Comment by michaelrice** [comment]
@erickmelo yeah I dont think the docs are done yet, but I can help you get it working. We have been using that plugin for about a year now. It works really well.

**Comment by budjb** [comment]
Docs are up now.  Great thing about the plugin is it doesn't require any configuration :)  It does require jaxrs 0.11 and spring security rc4, however.

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#9

**Comment by guramritpal-singh** [comment]
Is this issue was solved? I'm having the same issue. I think this is a configuration issue. Could you please assist me?
