### ISSUE TITLE
Problem with date in JSON if hour is 12 like : 2014-01-28T12:56:37Z

### ISSUE THREAD

**Issue by hakkanicko** [krasserm/grails-jaxrs#42]
Hi !

I have a weird issue. I have a domain class, like this : 
```groovy
class Test {
    Date date
    static constraints = {
    }
}
```
And a REST resource like this : 
```groovy
@Path('/api/test')
class TestResource {

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    Response postTestRepresentation(Test tr) {
        Response.ok(tr).build()
    }
}
```

In my REST client, if I post a JSON object on /api/test like this : 
```json
{"date":"2014-01-28T15:56:37Z"}
```
I get this, and it's fine : 
```json
{
"class": "api.Test"
"id": null
"date": "2014-01-28T15:56:37Z"
}
```

But if I post a date with hours set to 12, like : 
```json
{"date":"2014-01-28T12:56:37Z"}
```
I get my hour digits unmarshalled to 00 and I get this : 
```json
{
"class": "api.Test"
"id": null
"date": "2014-01-28T00:56:37Z"
}
```
By the way, I use Grails 2.3.5 and jaxrs:0.10.

If anybody have an explanation or/and a workaround, it will be great :)

Thanks.

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#10

**Comment by Nobhokleng** [comment]
> I guess it is due to the fact that you are passing both _T_ and _Z_ as constant chars within your json date(time) representation, where the literal 'Z' represents the UTC time zone.

Yes, thanks for your answer but I still have problem when it response as JSON with some data that I don't need look at below image:
![Screenshot from 2019-06-03 09-15-44](https://user-images.githubusercontent.com/48788312/58873423-88636880-86f0-11e9-97f2-889cfdeb7e68.png)
And this is what I need:
![Screenshot from 2019-06-03 09-23-13](https://user-images.githubusercontent.com/48788312/58873447-9618ee00-86f0-11e9-8e99-15b78a6bebb1.png)
