### ISSUE TITLE
Access Security Cookie in Resource class?

### ISSUE THREAD

**Issue by confile** [krasserm/grails-jaxrs#44]
I want to use a security cookie sent on each request between the server and the client. Is it possible to access request header information in my Resource classes to extract the security cookie X-CSRF-Token?

The security cookie could be the cookie from the JSESSIONID. Is it possible to reject the request if the secure cookie does not match?

Thank you for help. I really like your plugin.

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#11
