### ISSUE TITLE
How to output the POST request content?

### ISSUE THREAD

**Issue by stefaniebrunner** [krasserm/grails-jaxrs#49]
Hi, do you know how I can print or get out the content of a json-formatted POST request? My API received a json, but I don't know exactly how the structure of that json is. I tried a lot but I always reveive an error (a message body reader for Java class ... and Java type class was not found).
What can I do to find out what is in the request body? Thanks a lot.

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#14
