### ISSUE TITLE
Exception sending context initialized event to listener instance of class org.grails.jaxrs.web.JaxrsListener

### ISSUE THREAD

**Issue by blue-head** [krasserm/grails-jaxrs#51]
I kind of figure out a work-around, however, I wanted to post it to be taken into consideration ..

I followed the installation guide and things were okay and valid but I didn't create any resources(Jax-RS), just included the maven -repo and installed the plugin to my Grails project but when trying to start the app, I get the below exception which fails the whole initiation.
Exception sending context initialized event to listener instance of class org.grails.jaxrs.web.JaxrsListener

then I create a resource using the command line: grails create-resource <name>
and cleaned the app and tried to run again, and the error just gone. so that's illogical because you are forcing the app to run the command (grails create-resource) at least for one time ! 

Note: I am using GGTS 3.5.1 with Grails 2.3.9

Thank You

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#15
