### ISSUE TITLE
FileUpload with grails-jaxrs

### ISSUE THREAD

**Issue by confile** [krasserm/grails-jaxrs#52]
Does this plugin also support FileUpload with REST?

I an normal Grails controler action you would do something like this:

```
CommonsMultipartFile file = (CommonsMultipartFile) request.getFile('file')
```

How to I do fileupload in a rest resource to get the CommonsMultipartFile?

**Comment by prabhatsubedi** [comment]
Hi @confile , did you find solution? I am stuck here too ...

**Comment by confile** [comment]
No
