### ISSUE TITLE
Is it possible to use jackson 2.X with Jersey, and so use @JsonView

### ISSUE THREAD

**Issue by spirylics** [krasserm/grails-jaxrs#58]
I would like make that : 

    @GET
    @JsonView(Views.Name.class)
    List<User> list(@Context UriInfo uriInfo) {
        User.list(uriInfo.getQueryParameters())
    }

But @JsonView is not interpreted ; all user fields are returned.

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#19
