### ISSUE TITLE
Add support for Grails 3.x

### ISSUE THREAD

**Issue by hotmeatballsoup** [krasserm/grails-jaxrs#63]
Grails 3 is here - can we confirm that this plugin supports it in full?

**Comment by confile** [comment]
+1

**Comment by ericwubgl** [comment]
+1

**Comment by zverbatim** [comment]
+1

**Comment by noamt** [comment]
I'm really lacking the free time to do this upgrade, it would be really helpful if anyone can take it on: https://grails.github.io/grails-doc/latest/guide/upgrading.html

**Comment by noamt** [comment]
Created a new repo with some work I've begun doing - https://github.com/noamt/grails-jaxrs-plugin
Any help is greatly appreciated

**Comment by michaelrice** [comment]
Why did you make this a new project vs a new branch in the current project?

-mike

**Comment by noamt** [comment]
Martin has released ownership of the plugin long ago and upgrading the project changes the structure significantly so it's a good chance to start fresh

**Comment by donald-jackson** [comment]
Also adding my voice here, would love to have this upgraded. I have tried myself and made some progress, but keep getting stuck.

**Comment by donald-jackson** [comment]
If anyone on this thread is willing to help, I have a fork in progress here:

https://github.com/donald-jackson/grails-jaxrs

I have the plugin compiling correctly with Grails 3 and hooking in filters and actually processing the resource classes, just having some issues with processing complex objects. Perhaps someone else can take a look to see what I'm missing? Issue details are in README.md

@noamt @krasserm

**Comment by krasserm** [comment]
@donald-jackson what speaks against using https://github.com/noamt/grails-jaxrs-plugin ? @noamt do you still maintain that project?

**Comment by donald-jackson** [comment]
@krasserm Sorry I didn't even know about it. Will re-fork.

**Comment by noamt** [comment]
Sorry, all.
I have no more time to maintain this project.

**Comment by krasserm** [comment]
@noamt Would you be interested contributing back your changes to a separate branch in this project? Or anyone else?

**Comment by donald-jackson** [comment]
@krasserm - as I say I have this plugin working in grails 3 now in the repo I mentioned above. I also have Spring Security Jaxrs & Swagger4Jaxrs now working. Its just a matter of refactoring the tests now, but the project itself works.

**Comment by krasserm** [comment]
@donald-jackson great, thanks!

**Comment by donald-jackson** [comment]
@krasserm once I have the tests functional I will do a pull request to the original repo :+1:

**Comment by krasserm** [comment]
@donald-jackson looking forward to it :smiley:
