### ISSUE TITLE
Renderer makes date property null before db operation

### ISSUE THREAD

**Issue by daptordarattler** [krasserm/grails-jaxrs#64]
I have a date property on a domain model
```
Consignment{
       String  description
       Date dateDone

       Date dateCreated
       Date lastUpdated
}
```

Any time I update the dateDone from the client with javascript using code
```
consignment.dateDone = new Date().toISOString()
```

it is nulled in the resource code before even getting to the service operations
I have no Idea why. Its got me pulling out my hair all day.

**Comment by noamt** [comment]
If you've got trouble debugging it, please post an example project or create a pull request with a test that reproduces it.

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#23

**Comment by daptordarattler** [comment]
I had the same problem for a long time and only recently solved it. The
grails data binding for date formats does not bind with the javascript
multiple date formats well so you have to add some date format patterns in
Config.groovy to fix this.

Here is the code I used:

```


//compatible with dates expressed as "2014-01-28T12:56:37+0100" as a
wider range of date patterns
grails.databinding.dateFormats = ['yyyy-MM-dd HH:mm:ss.S',"yyyy-MM-dd
HH:mm:ss.S z",
                          'yyyy-MM-dd HH:mm:ss.SSS',"yyyy-MM-dd HH:mm:ss.SSS z",
                          "yyyy-MM-dd HH:mm:ss.SSS'Z'","yyyy-MM-dd
HH:mm:ss.s'Z'",

"yyyy-MM-dd'T'HH:mm:ss'Z'","yyyy-MM-dd'T'HH:mm:ss.SSS'Z'","yyyy-MM-dd'T'HH:mm:ss.S'Z'",
                          "EEE MMM dd yyyy HH:mm:ss 'GMT'Z (z)"]

```

On Thu, Mar 31, 2016 at 5:50 PM, Bud Byrd <notifications@github.com> wrote:

> This issue was moved to budjb/grails-jaxrs#23
> <https://github.com/budjb/grails-jaxrs/issues/23>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/krasserm/grails-jaxrs/issues/64#issuecomment-204049742>
>



-- 
Dominic Fui Dodzi-Nusenu
Enterpreneur / Software Developer
0202415379

**Comment by daptordarattler** [comment]
I had the same problem for a long time and only recently solved it. The
grails data binding for date formats does not bind with the javascript
multiple date formats well so you have to add some date format patterns in
Config.groovy to fix this.

Here is the code I used:
```
//compatible with dates expressed as "2014-01-28T12:56:37+0100" as a wider range of date patterns
grails.databinding.dateFormats = ['yyyy-MM-dd HH:mm:ss.S',"yyyy-MM-dd HH:mm:ss.S z",
                          'yyyy-MM-dd HH:mm:ss.SSS',"yyyy-MM-dd HH:mm:ss.SSS z", 
                           "yyyy-MM-dd HH:mm:ss.SSS'Z'","yyyy-MM-ddHH:mm:ss.s'Z'","yyyy-MM-dd'T'HH:mm:ss'Z'",
                           "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'","yyyy-MM-dd'T'HH:mm:ss.S'Z'",
                           "EEE MMM dd yyyy HH:mm:ss 'GMT'Z (z)"]
```
