### ISSUE TITLE
How to get actual uri (i.e) api/v1/login/1234 instead of /grails/jaxrs.dispatch

### ISSUE THREAD

**Issue by lakshmipmandava** [krasserm/grails-jaxrs#66]
We are trying to get the actual uri in Grails filter 

         testUris(uri:'/api/**') {
               before = {
                    println("before ----------------"+request.getRequestURI())
                   // do some preprocessing
               }
                after = {
                     println("sdafter ----------------"+request.getRequestURI())
                   // do some postprocessing
                 }
         } 

using above code. but its it printing  /grails/jaxrs.dispatch instead of api/v1/login/1234

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#24
