### ISSUE TITLE
Grails JaxRs Plugin compilation error

### ISSUE THREAD

**Issue by vinod-bb** [krasserm/grails-jaxrs#68]
I am using grails jaxrs plugin with Grails 2.2.4

grails.project.dependency.resolution = {
    plugins {
        compile ':jaxrs:0.8'
    }
}

During compilation of my Grails Application and i get the below error

`/plugins/jaxrs-0.8/src/java/org/springframework/mock/web/DelegatingServletInputStream.java:39: error: DelegatingServletInputStream is not abstract and does not override abstract method setReadListener(ReadListener) in ServletInputStream
public class DelegatingServletInputStream extends ServletInputStream {`

Please help

**Comment by budjb** [comment]
This issue was moved to budjb/grails-jaxrs#1
